- platform: template
  sensors:
    bathroom_temperature:
      friendly_name: 'Living room temperature'
      value_template: '{{states.sensor.bad_motion_sensor.attributes.temperature}}'
      unit_of_measurement: °C

    bathroom_light_level:
      friendly_name: 'Living room light level'
      value_template: '{{states.sensor.bad_motion_sensor.attributes.lx}}'
      unit_of_measurement: lux
