- platform: template
  sensors:
    3d_drucker_power:
      friendly_name: "3D Drucker"
      value_template: "{{ states.switch['3d_drucker'].attributes.current_power_w }}"
      unit_of_measurement: W

    nas_power:
      friendly_name: "NAS"
      value_template: "{{ states.switch.nas.attributes.current_power_w }}"
      unit_of_measurement: W

    tvmedia_power:
      friendly_name: "TV/Media"
      value_template: "{{ states.switch.tvmedia.attributes.current_power_w }}"
      unit_of_measurement: W

    waschmaschine_power:
      friendly_name: "Waschmaschine"
      value_template: "{{ states.switch.waschmaschine.attributes.current_power_w }}"
      unit_of_measurement: W
