default_view:
  name: "Übersicht"
  view: yes
  entities:
    - group.family_presence
    - group.heating
    - group.weather
    - group.octoprint
    - group.container_and_services
    - history_graph.edgemax_throughput
    - history_graph.stromverbrauch
    - history_graph.internet_speedtest

heating:
  name: Heizung
  entities:
    - climate.jonas
    - climate.marian

family_presence:
  name: Anwesenheit
  entities:
    - group.human_jonas
    - group.human_marian

weather:
  name: Wetter
  entities:
    - sensor.dark_sky_summary
    - sensor.dark_sky_temperature
    - sensor.dark_sky_precip_probability
    - sensor.dark_sky_cloud_coverage

container_and_services:
  name: Containers / Services
  entities:
    - binary_sensor.container_locked_bazarr
    - binary_sensor.container_locked_hass
    - binary_sensor.container_locked_muximux
    - binary_sensor.container_locked_netdata
    - binary_sensor.container_locked_ombi
    - binary_sensor.container_locked_openvpn
    - binary_sensor.container_locked_oscarr
    - binary_sensor.container_locked_owntracks
    - binary_sensor.container_locked_plex
    - binary_sensor.container_locked_radarr
    - binary_sensor.container_locked_radarrbot
    - binary_sensor.container_locked_sabnzbd
    - binary_sensor.container_locked_sonarr
    - binary_sensor.container_locked_sonarrbot
    - binary_sensor.container_locked_speedtester
    - binary_sensor.container_locked_unifi
    - binary_sensor.tcp_octoprint
