# Reorder group tabs
group.default_view:
  order: 1
group.jonas:
  order: 2
group.marian:
  order: 3
group.corridor:
  order: 4
group.kitchen:
  order: 5
group.office:
  order: 6
group.bathroom:
  order: 7

# Hide NAS group to prevent someone turning off its switch
group.nas:
  hidden: true
