homeassistant:
  name: Friedmann HQ
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml

group: !include_dir_merge_named groups
sensor: !include sensors.yaml
automation: !include automations.yaml
script: !include scripts.yaml

logger:
  default: error
  logs:
    homeassistant.components.shell_command: debug

octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_key
  bed: true
  number_of_tools: 1

device_tracker:
  - platform: icloud
    username: !secret icloud_jonas_user
    password: !secret icloud_jonas_pass
  - platform: icloud
    username: !secret icloud_marian_user
    password: !secret icloud_marian_pass

camera:
  - platform: mjpeg
    name: octoprint
    still_image_url: !secret octoprint_webcam_still
    mjpeg_url: !secret octoprint_webcam_stream

tado:
  username: !secret tado_user
  password: !secret tado_pass

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access
    aws_secret_access_key: !secret aws_secret

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret hass_api_pass

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Cloud
cloud:
