# Dark Sky friendly names

sensor.dark_sky_cloud_coverage:
  friendly_name: Bedeckungsgrad
sensor.dark_sky_precip_probability:
  friendly_name: Regenwahrscheinlichkeit
sensor.dark_sky_summary:
  friendly_name: Überblick
sensor.dark_sky_temperature:
  friendly_name: Termperatur

# Ender 3 friendly names

sensor.octoprint_actual_bed_temp:
  friendly_name: Bett IST
  icon: mdi:thermometer
sensor.octoprint_actual_tool0_temp:
  friendly_name: Düse IST
  icon: mdi:thermometer
sensor.octoprint_current_state:
  friendly_name: Aktueller Zustand
  icon: mdi:printer-3d
sensor.octoprint_job_percentage:
  icon: mdi:percent
  friendly_name: Job %
sensor.octoprint_target_bed_temp:
  friendly_name: Bett SOLL
  icon: mdi:thermometer
sensor.octoprint_target_tool0_temp:
  friendly_name: Düse SOLL
  icon: mdi:thermometer

# Tado heating/climate names

sensor.jonas_humidity:
  friendly_name: Luftfeuchtigkeit
sensor.marian_humidity:
  friendly_name: Luftfeuchtigkeit
sensor.jonas_heating:
  friendly_name: Heiz-Zustand
sensor.marian_heating:
  friendly_name: Heiz-Zustand
