- platform: darksky
  api_key: !secret darksky_key
  language: de
  monitored_conditions:
    - cloud_cover
    - precip_probability
    - summary
    - temperature

- platform: octoprint
  name: OctoPrint
  monitored_conditions:
    - Current State
    - Temperatures
    - Job Percentage
    - Time Elapsed
    - Time Remaining

- platform: template
  sensors:
    3d_drucker_power:
      value_template: {{ states.switch.3d_drucker.attributes.current_power_w }}
      unit_of_measurement: W

- platform: template
  sensors:
    nas_power:
      value_template: {{ states.switch.nas.attributes.current_power_w }}
      unit_of_measurement: W

- platform: template
  sensors:
    tvmedia_power:
      value_template: {{ states.switch.tvmedia.attributes.current_power_w }}
      unit_of_measurement: W

- platform: template
  sensors:
    waschmaschine_power:
      value_template: {{ states.switch.waschmaschine.attributes.current_power_w }}
      unit_of_measurement: W
