- platform: darksky
  api_key: !secret darksky_key
  language: de
  monitored_conditions:
    - cloud_cover
    - precip_probability
    - summary
    - temperature

- platform: octoprint
  name: OctoPrint
  monitored_conditions:
    - Current State
    - Temperatures
    - Job Percentage
    - Time Elapsed
    - Time Remaining
