  - platform: tplink
    host: !secret hs110-1_host
  - platform: tplink
    host: !secret hs110-2_host
  - platform: tplink
    host: !secret hs110-2_host
  - platform: tplink
    host: !secret hs110-3_host
