default_view:
  name: "Home"
  view: yes
  entities:
    - group.weather

weather:
  name: Familie
  entities:
  - sensor.dark_sky_summary
  - sensor.dark_sky_temperature
  - sensor.dark_sky_precip_probability
  - sensor.dark_sky_cloud_coverage
