default_view:
  name: "Home"
  view: yes
  entities:
    - group.family_info
    - group.heating
    - group.weather

heating:
  name: Heizung
  entities:
    - climate.jonas
    - climate.marian

family_info:
  name: Familie
  entities:
    - group.human_jonas
    - group.human_marian

weather:
  name: Wetter
  entities:
  - sensor.dark_sky_summary
  - sensor.dark_sky_temperature
  - sensor.dark_sky_precip_probability
  - sensor.dark_sky_cloud_coverage
