marian:
  name: Marian
  view: yes
  entities:
    - group.marian_lights

marian_lights:
  - light.deckenlampe_4
  - light.bodenlampe
  - light.fernsehlampe
  - light.nachttisch_links
  - light.nachttisch_rechts
