family:
  name: Familie
  entities:
    - group.human_jonas
    - group.human_marian

human_jonas:
  name: Jonas
  entities:
    - !secret device_jonas_iphone-gps

human_marian:
  name: Marian
  entities:
    - !secret device_marian_iphone-gps
