familie:
  name: Familie
  entities:
    - group.jonas
    - group.marian

jonas:
  name: Jonas
  entities:
    - device_tracker.iphone

marian:
  name: Marian
  entities:
    - device_tracker.iphonevriedmann
