familie:
  name: Familie
  entities:
    - group.jonas
    - group.marian

human_jonas:
  name: Jonas
  entities:
    - !secret device_jonas-iphone

human_marian:
  name: Marian
  entities:
    - !secret device_marian-iphone
