jonas:
  name: Jonas
  view: yes
  entities:
    - group.jonas_lights
    - group.jonas_climate
    - group.media
    - history_graph.stromverbrauch

jonas_lights:
  name: Jonas' Lampen
  entities:
    - light.deckenlampe_5
    - light.stehlampe

jonas_climate:
  name: Heizung/Klima
  entities:
    - climate.jonas
    - sensor.jonas_humidity
    - sensor.jonas_heating

media:
  name: TV/Media
  entities:
    - switch.tvmedia
