marian:
  name: Marian
  view: yes
  entities:
    - group.marian_lights
    - group.marian_climate

marian_lights:
  name: Marian's Lampen
  entities:
    - light.deckenlampe_4
    - light.bodenlampe
    - light.fernsehlampe
    - light.nachttisch_links
    - light.nachttisch_rechts

marian_climate:
  name: Heizung/Klima
  entities:
    - climate.marian
    - sensor.marian_humidity
    - sensor.marian_heating
