bad:
  name: Bad
  view: yes
  entities:
    - group.bad_lights
    - group.washer
    - history_graph.stromverbrauch_bad

bad_lights:
  name: Bad Lampen
  entities:
    - light.deckenlampe_3

washer:
  name: Waschmaschine
  entities:
    - switch.waschmaschine
