buero:
  name: Büro
  view: yes
  entities:
    - group.buero_lights
    - group.octoprint
    - group.nas

buero_lights:
  name: Büro Lampen
  entities:
    - light.deckenlampe_6

octoprint:
  name: Ender 3
  entities:
    - switch.3d_drucker
    - sensor.octoprint_actual_bed_temp
    - sensor.octoprint_actual_tool0_temp
    - sensor.octoprint_current_state
    - sensor.octoprint_job_percentage
    - sensor.octoprint_target_bed_temp
    - sensor.octoprint_target_tool0_temp
    - camera.octoprint

nas:
  name: NAS
  entities:
    - switch.nas
    - group.container_and_services
