bad:
  name: Bad
  view: yes
  entities:
    - group.bathroom_general
    - group.washer
    - history_graph.stromverbrauch_bad

bathroom_general:
  name: Bad
  entities:
    - light.deckenlampe_3
    - sensor.bathroom_light_level
    - sensor.bathroom_temperature

washer:
  name: Waschmaschine
  entities:
    - switch.waschmaschine
