- id: arrive_home_notification
  alias: Send notifications when someone arrives at home
  trigger:
    platform: state
    from: "not_home"
    to: "home"
    entity_id:
      - group.human_jonas
      - group.human_marian
  action:
    service: notify.telegram_jonas
    data_template:
      message: >
        {{ trigger.from_state.attributes.friendly_name }} ist Zuhause angekommen!

- id: leave_home_notification
  alias: Send notifications when someone leaves from home
  trigger:
    platform: state
    from: "home"
    to: "not_home"
    entity_id:
      - group.human_jonas
      - group.human_marian
  action:
    service: notify.telegram_jonas
    data_template:
      message: >
        {{ trigger.from_state.attributes.friendly_name }} hat die Wohnung verlassen!
