homeassistant:
  name: Friedmann HQ
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include_dir_merge_named customize

group: !include_dir_merge_named groups
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
automation: !include automations.yaml
script: !include scripts.yaml
binary_sensor: !include_dir_merge_list binary_sensors
history_graph: !include_dir_merge_named history_graphs

logger:
  default: error
  logs:
    homeassistant.components.shell_command: debug

mqtt:
  discovery: true
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_key
  bed: true
  number_of_tools: 1

camera:
  - platform: mjpeg
    name: octoprint
    still_image_url: !secret octoprint_webcam_still
    mjpeg_url: !secret octoprint_webcam_stream

tado:
  username: !secret tado_user
  password: !secret tado_pass

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access
    aws_secret_access_key: !secret aws_secret

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chatid_jonas

notify:
  - name: telegram_jonas
    platform: telegram
    chat_id: !secret telegram_chatid_jonas

homekit:
  filter:
    include_domains:
      - light

discovery:
  ignore:
    - plex_mediaserver

frontend:

config:

http:
  api_password: !secret hass_api_pass

updater:

conversation:

history:

logbook:

map:

sun:

cloud:
