- platform: template
  sensors:
    container_locked_bazarr:
      friendly_name: Bazarr
      value_template: "{{ is_state('switch.container_bazarr', 'on') }}"

- platform: template
  sensors:
    container_locked_grafana:
      friendly_name: Grafana
      value_template: "{{ is_state('switch.container_grafana', 'on') }}"

- platform: template
  sensors:
    container_locked_hass:
      friendly_name: Home Assistant
      value_template: "{{ is_state('switch.container_hass', 'on') }}"

- platform: template
  sensors:
    container_locked_influxdb:
      friendly_name: InfluxDB
      value_template: "{{ is_state('switch.container_influxdb', 'on') }}"

- platform: template
  sensors:
    container_locked_muximux:
      friendly_name: Muximux
      value_template: "{{ is_state('switch.container_muximux', 'on') }}"

- platform: template
  sensors:
    container_locked_ombi:
      friendly_name: Ombi
      value_template: "{{ is_state('switch.container_ombi', 'on') }}"

- platform: template
  sensors:
    container_locked_oscarr:
      friendly_name: Oscarr
      value_template: "{{ is_state('switch.container_oscarr', 'on') }}"

- platform: template
  sensors:
    container_locked_openvpn:
      friendly_name: OpenVPN
      value_template: "{{ is_state('switch.container_openvpn', 'on') }}"

- platform: template
  sensors:
    container_locked_owntracks:
      friendly_name: OwnTracks
      value_template: "{{ is_state('switch.container_owntracks', 'on') }}"

- platform: template
  sensors:
    container_locked_plex:
      friendly_name: Plex Media Server
      value_template: "{{ is_state('switch.container_plex', 'on') }}"

- platform: template
  sensors:
    container_locked_radarr:
      friendly_name: Radarr
      value_template: "{{ is_state('switch.container_radarr', 'on') }}"

- platform: template
  sensors:
    container_locked_radarrbot:
      friendly_name: Radarr Telegram Bot
      value_template: "{{ is_state('switch.container_radarrbot', 'on') }}"

- platform: template
  sensors:
    container_locked_sabnzbd:
      friendly_name: SabNZBd
      value_template: "{{ is_state('switch.container_sabnzbd', 'on') }}"

- platform: template
  sensors:
    container_locked_sonarr:
      friendly_name: Sonarr
      value_template: "{{ is_state('switch.container_sonarr', 'on') }}"

- platform: template
  sensors:
    container_locked_sonarrbot:
      friendly_name: Sonarr Telegram Bot
      value_template: "{{ is_state('switch.container_sonarrbot', 'on') }}"

- platform: template
  sensors:
    container_locked_speedtest:
      friendly_name: Speedtest
      value_template: "{{ is_state('switch.container_speedtest', 'on') }}"

- platform: template
  sensors:
    container_locked_unifi:
      friendly_name: UniFi WiFi Controller
      value_template: "{{ is_state('switch.container_unifi', 'on') }}"
